## Assignment 9

### Problem

Find a suitable Python library that implements the exponential smoothing method. Solve the Regens Book problem.

### Resolution

We can use the function _ExponentialSmoothing_ from _statsmodels.tsa.holtwinters_.

In [1]:
from statsmodels.tsa.holtwinters import ExponentialSmoothing
import numpy as np


# prepare data
data = np.array([[1, 89], [2, 106], [3, 92], [4, 98], [5, 77], [6, 80], [7, 88], [8, 87],  [9, 92], [10, 86]])
data = np.array([89, 106, 92, 98, 77,80,88,87,92,86])
# create class
model = ExponentialSmoothing(data.astype(np.double))
# fit model
model_fit = model.fit()
# make prediction
yhat = model_fit.predict()

In [2]:
print(data)

[ 89 106  92  98  77  80  88  87  92  86]


In [3]:
print(model_fit)
print(yhat)

[89.49999991]


In [4]:
data=np.append(data,88)
print(data)
# create class
model = ExponentialSmoothing(data.astype(np.double))
# fit model
model_fit = model.fit()
# make prediction
yhat = model_fit.predict()
print(yhat)

[ 89 106  92  98  77  80  88  87  92  86  88]
[89.36363644]


In [5]:
data=np.append(data,int(yhat))
print(data)

[ 89 106  92  98  77  80  88  87  92  86  88  89]


In [6]:
# create class
model = ExponentialSmoothing(data.astype(np.double))
# fit model
model_fit = model.fit()
# make prediction
yhat = model_fit.predict()
print(yhat)

[89.33333318]


In [7]:
data=np.append(data,int(yhat))
print(data)
# create class
model = ExponentialSmoothing(data.astype(np.double))
# fit model
model_fit = model.fit()
# make prediction
yhat = model_fit.predict()
print(yhat)

[ 89 106  92  98  77  80  88  87  92  86  88  89  89]
[89.30769219]
